-- ====================================================================
-- SUPABASE STATUS SETUP SCRIPT - MS MODA ÍNTIMA (ATELIER)
-- Run this script inside the "SQL Editor" in your Supabase Dashboard.
-- This script configures all data tables with strict User separation
-- using Row Level Security (RLS). Here is how:
-- ====================================================================

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'INFLOW' or 'OUTFLOW'
    user_id UUID NOT NULL DEFAULT auth.uid()
);

-- 2. TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    type TEXT NOT NULL, -- 'INFLOW' or 'OUTFLOW'
    category TEXT NOT NULL,
    dateString TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    extraText TEXT DEFAULT '',
    week TEXT DEFAULT '1ª Semana',
    user_id UUID NOT NULL DEFAULT auth.uid()
);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientName TEXT NOT NULL,
    pantyType TEXT NOT NULL,
    pantySize TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    pantyValue DOUBLE PRECISION NOT NULL,
    totalValue DOUBLE PRECISION NOT NULL,
    week TEXT NOT NULL,
    user_id UUID NOT NULL DEFAULT auth.uid()
);

-- 4. PIECE CALCULATIONS TABLE
CREATE TABLE IF NOT EXISTS public.piece_calculations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pano TEXT NOT NULL,
    kg DOUBLE PRECISION,
    valorKg DOUBLE PRECISION,
    quantidade INTEGER,
    user_id UUID NOT NULL DEFAULT auth.uid()
);


-- ====================================================================
-- ROW LEVEL SECURITY (RLS) SETUP
-- Prevents users from seeing other users' data! Perfect security.
-- ====================================================================

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.piece_calculations ENABLE ROW LEVEL SECURITY;

-- CATEGORIES POLICIES
CREATE POLICY "Users can manage their own categories" 
ON public.categories FOR ALL 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- TRANSACTIONS POLICIES
CREATE POLICY "Users can manage their own transactions" 
ON public.transactions FOR ALL 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- ORDERS POLICIES
CREATE POLICY "Users can manage their own orders" 
ON public.orders FOR ALL 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- PIECE CALCULATIONS POLICIES
CREATE POLICY "Users can manage their own piece calculations" 
ON public.piece_calculations FOR ALL 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);


-- ====================================================================
-- REALTIME SUBSCRIPTION OR CONVENIENT INTEGRATION INDEXES
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_categories_user ON public.categories(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_piece_calcs_user ON public.piece_calculations(user_id);
